version: "3.8"

networks:
  front-net:

services:
    nudoxfront:
        #container_name: nuboxapp
        build: ../nuboxapp
        networks:
            - front-net
        ports:
            - "3500:3500"